export type ActionTypes =
  | 'FETCH'
  | 'ENABLE_LOADER'
  | 'DESABLE_LOADER'
  | 'ENABLE_LOAD_DATA'
  | 'DESABLE_LOAD_DATA'
  | 'SET_PHONE'
  | 'SET_MANUFACTURER'
  | 'SET_LOCATION'
  | 'SET_TOKEN'
  | 'SET_CURRENT_TOKEN'
  | 'SET_OTP_ERROR'
  | 'SET_CARS'
  | 'SET_SELECTED_CAR'
  | 'SET_USER_DATA'
  | 'SET_DEALER'
  | 'SET_CLOSED_DAYS'
  | 'SET_CAR_TYPE'
  | 'SET_CAR_SERVICE'
  | 'SET_BOOKING_PERSONAL_DATA'
  | 'SET_CAR_HISTORY'
  | 'CAR_UPDATED'
  | 'CLEAR_MESSAGE_ERROR'
  | 'LOGOUT';

const FETCH = 'FETCH';
const ENABLE_LOADER = 'ENABLE_LOADER';
const ENABLE_LOAD_DATA = 'ENABLE_LOAD_DATA';
const DESABLE_LOAD_DATA = 'DESABLE_LOAD_DATA';
const DESABLE_LOADER = 'DESABLE_LOADER';
const SET_PHONE = 'SET_PHONE';
const SET_MANUFACTURER = 'SET_MANUFACTURER';
const SET_LOCATION = 'SET_LOCATION';
const SET_TOKEN = 'SET_TOKEN';
const SET_CURRENT_TOKEN = 'SET_CURRENT_TOKEN';
const SET_OTP_ERROR = 'SET_OTP_ERROR';
const SET_CARS = 'SET_CARS';
const SET_SELECTED_CAR = 'SET_SELECTED_CAR';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_DEALER = 'SET_DEALER';
const SET_CLOSED_DAYS = 'SET_CLOSED_DAYS';
const SET_CAR_TYPE = 'SET_CAR_TYPE';
const SET_CAR_SERVICE = 'SET_CAR_SERVICE';
const SET_BOOKING_PERSONAL_DATA = 'SET_BOOKING_PERSONAL_DATA';
const SET_CAR_HISTORY = 'SET_CAR_HISTORY';
const CAR_UPDATED = 'CAR_UPDATED';
const CLEAR_MESSAGE_ERROR = 'CLEAR_MESSAGE_ERROR';
const LOGOUT = 'LOGOUT';

export {
  FETCH,
  ENABLE_LOADER,
  ENABLE_LOAD_DATA,
  DESABLE_LOADER,
  DESABLE_LOAD_DATA,
  SET_MANUFACTURER,
  SET_PHONE,
  SET_LOCATION,
  SET_TOKEN,
  SET_CURRENT_TOKEN,
  SET_OTP_ERROR,
  SET_CARS,
  SET_SELECTED_CAR,
  SET_USER_DATA,
  SET_DEALER,
  SET_CLOSED_DAYS,
  SET_CAR_SERVICE,
  SET_CAR_TYPE,
  SET_BOOKING_PERSONAL_DATA,
  SET_CAR_HISTORY,
  CAR_UPDATED,
  CLEAR_MESSAGE_ERROR,
  LOGOUT,
};
